var names=new Array( 
// from samantha bee    http://www.slate.com/blogs/browbeat/2016/11/05/here_s_everything_samantha_bee_has_called_donald_trump.html
"Sentient caps-lock button",
"Freshly sandpapered reality star",
"Two-bit wall salesman",
"Melting hunk of uninformed apricot Jell-O",
"Erratic rage quasar",
"America's first appendix",
"Backfired wish that Republicans made on a cursed monkey's paw",
"Agent Orange",
"Bigoted See 'n Say",
"Dauphin of Breitbartistan",
"Demagoguing bag of candy corn",
"George Wallace in a wig",
"Cheap National Front knockoff",
"Muddled asshole yearning to scream free",
"Big hairy orange villain",
"Leering dildo",
"M. Night Orangeman",
"Grotesque caterpillar turning into a somehow even more grotesque butterfly",
"Heretical billionaire bully",
"Nativist foghorn",
"Crotch-fondling slab of rancid meatloaf",
"Casino Mussolini",
"Monstrous apricot bulb",
"Hometown embarrassment",
"Screaming carrot demon",
"First-grader with a head injury",
"16-month Hindenburg explosion",
"Orange supremacist",
"Sociopathic 70-year-old toddler",
"Failed QVC steak salesman",
"Nasty garbage monster",
"The white power movement's orange ally",
"Thrice-married foul-mouthed tit judge who likes Planned Parenthood and thinks Corinthians is a type of car upholstery",
"Two-bit used hate salesman",
"The asteroid that just destroyed a party of dinosaurs",
"Dick-waving Berlusconi knockoff",
"Fat Elvis",
"Large-mouthed ass",
"Creamsicle",
"Rich asshole who wants to be king of America",
"Tangerine tinted trash can fire",
"Tax-cheating, investor-swindling, worker-shafting, dictator-loving, pathologically lying, attorneys general-bribing, philandering, mobbed up, narcissistic serial con artist",
"The least qualified candidate ever to lurch into the public spotlight and shit on Gold Star moms while cradling Putin's sweaty sack",
// others
"Cheeto Mussolini",    
"Dolt 45",
// https://bullshit.ist/50-nicknames-for-donald-trump-you-wont-be-hearing-on-fox-news-7b7a5ca1b1b1
"Adolf Twitler",
"Agent Orange",
"The Angry Creamsicle",
"Barbecued Brutus",
"Benedict Donald",
"Boss Tweet",
"Bratman",
"Cheeto Benito",
"Cheeto-In-Chief",
"The Combover Con Artist",
"Comrade Cheetolino",
"Creep Throat",
"Crown Prince of Politwits",
"Darth Hater",
"Donald Chump",
"Donnie Bratso",
"Donnie TicTac",
"Draft Dodger Don",
"Dumbelldore",
"The Fanta Fascist",
"The Fraud of Fifth Avenue",
"Fuckface Von Clownstick",
"Genghis Can't",
"The Golden Wrecking Ball",
"The Great White Dope",
"Hair Furher",
"The Human Tanning Bed Warning Label",
"The Infuriator",
"Last Of The Mango Mohawkans",
"Little Lady Fingers",
"King Leer",
"The Lone DeRanger",
"The Lyin King",
"Macho McGrump",
"Mango Mussolini",
"President Gold Man Sucks",
"President If-Urine-You're-In",
"President Rancid Velveeta",
"Prima Donald",
"Pudgy McTrumpcake",
"Putin's Papaya-Flavored Pawn",
"Short-Fingered Vulgarian",
"Sir Sissypants",
"The Talking Yam",
"Tangerine Tornado",
"Tie-Coon",
"Trumplethinskin",
"Trumpty Dumpty",
"Vanilla ISIS",
"The White Pride Piper",
// http://www.thehypertexts.com/Donald%20Trump%20Nicknames.htm
"Putin's Puppet",
"Putin's Bitch",
"Putin's Lapdog",
"Putin's Cock-Holster",
"Putin's Useful Idiot",
"Comrade Trumputin",
"The Brooklyn Bolshevik",
"The Russian Mole",
"Cheeto-Dusted Bloviator",
"Screaming Cheeto",
"Cheeto Benito",
"Cheez Whiz",
"Mango Mussolini",
"Cinnamon Hitler",
"Candied Yam",
"Angry Creamsicle",
"Fanta Ranter",
"Trumpster Fire",
"Orange Julius",
"Orange Foolius  ",
"Lord Voldemort",
"Orange Anus",
"Snake Oil Salesman",
"Golden Wrecking Ball",
"Fuckface von Clownstick",
"Man-Baby",
"Comedy Entrapment",
"Unrepentant Narcissistic Asshole",
"The White Kanye",
"Short-Fingered Vulgarian",
"Tiny Hands Trump",
"Babyfingers Trump",
"Pixie Fingers Trump",
"The Tiny-Handed Tyrant",
"Stumpy",
"Chubby Nubby",
"Short-Fingered Totalitarian",
"Agent Orange",
"The Trump of Doom",
"The Antichrist",
"Prima Donald",
"The Hunchback of Notre Shame",
"Shambling Sasquatch",
// http://www.citypages.com/news/the-20-best-nicknames-for-donald-trump-so-far/389377462
"Agent Orange",
"Bratman",
"The Human Corncob",
"Darth Hater",
"Hair Furher",
"K-Mart Caesar",
"The Angry Cheeto",
"Genghis Can't",
"The Xenophobic Sweet Potato",
"Prima Donald",
"Barbecued Brutus",
"The White Kanye",
"Dire Abby",
"The Tanning Bed Warning Label",
"Tangerine Jesus",
"The Feral Shouting Meatball",
"Vanilla ISIS",
"The Talking Yam",
"Mango Mussolini",
"Cinnamon Hitler",
// http://web.blomand.net/~dennmac/reich-wing/donaldtrumpnicknames.html
"Agent Orange",
"Babyfingers",
"Birther Boy",
"Bratman",
"Cheeto Benito",
"Cheeto Jesus",
"Cinnamon Hitler",
"Darth Hater",
"Donnie Darko",
"Dumb Corleone",
"Dumbelldore",
"Forrest Trump",
"Fuckface von Clownstick",
"Genghis Can't",
"Hair Furor",
"Hair Trump",
"Humpty Trumpty",
"Mein Trumpf",
"Mr. Wiggy Piggy",
"Mussolini's Taint",
"POTUS Wrecks",
"Prima Donald",
"Puffed Up Daddy",
"The Angry Pumpkin",
"The Combover Kid",
"The Commander-in-Grief",
"The Dick-Tater",
"The New York Pork Dork",
"The Presumptuous Nominee",
"The Short Fingered Vulgarian",
"The Talking Yam",
"The Tangerine Tornado",
"The Tiny Handed Tyrant",
"The Tufted Taliban",
"The White Kanye",
"Thurston Shitbag the Third",
"Trumplethinskin",
"Trumpty Dumpty",
"Trumpy Cat",
"Vanilla ISIS",
// http://www.cc.com/video-clips/tt5w0h/the-daily-show-with-trevor-noah-exclusive---trevor-s-many-nicknames-for-trump
"Pile of old garbage covered with vodka sauce",
"Butternut squash who wished upon a shooting star and became a real live boy",
"Traffic cone soaked in raw sewage",
"Day old mayonnaise sculpture",
"Chairman of the Saddam Hussein fan club",
"Self-financed melting jack-o-lantern",
"Empty sack of hot air",
"Mutant from a carrot-juicing accident",
"Cancer in a wig",
"Pumpkin in a suit",
"The uncle who hits on your wife at funerals",
"Expired bottle of Sunny Delight",
"Racist clementine",
"Weirdest and most conspiratorial nutjob on the message board",
"Half-melted Push Pop",
"Pile of cheesy slop stuffed inside a thin orange shell",
"Six foot pile of angry carrot cake vomit",
"Torture-supporting Muslim-disparaging horseman of the apocalypse",
// https://www.reddit.com/r/TrumpNicknames
"Cheeto Benito",
"Super Callous Fragile Racist Extra Braggadocious",
"Trumplethinskin",
"GropenFührer",
"Snowflake in Chief",
"Twitler",
"Dorito Mussolini",
"Fuckface Von Clownstick",
"PrimaDonald",
"Mango Mussolini",
"Tangerine Palpatine",
"L. Don Tubbard",
"Fascist, loofa-faced shit-gibbon",
"Il Douche",
"So-Called Ruler Of The United States (SCROTUS)",
"Commander in Tweet",
"Scandalf the Orange",
"The Kremlin Gremlin",
"Don the Con",
"Bannon's Bitch",
"The Mango Molester",
"Trumpster Fire",
"The Fanta Fascist",
"The Apricot Pol Pot",
"Agent Orange",
"Mandarin Messiah",
"Fucking idiot.",
"Twitler",
"Gross Domestic Product",
"Persimmon Palpatine",
"The Siberian Candidate",
"Midget Digits",
"Pumpkin Pinochet",
"The Prima Donald",
"Twitler",
"Ku Klux Klown",
"Orange is the new black",
"Taking a Trump",
"Tangerine Tyrant",
"Sir Orange Dickblossom of the Flaxen Weave",
"Emperor Hirocheeto",
"The Banana Republican",
"Trumplethinskin",
"Orange Foolius",
"Donny Two Scoops",
"Clementine Caligula",
"Tweety Amin",
"Hillbilly Hitler",
"The Ochre Joker",
"Schmuck a l'Orange",
// scottish nicknames  https://9gag.com/gag/abZy938/scots-shower-trump-with-glorious-scottish-insults-after-his-brexit-tweet
"Weapons-grade plum",
"Utter twonk",
"Witless fucking cocksplat",
"Weaselheaded fucknugget",
"Mangled apricot hellbeast",
"Clueless numpty",
"Bloviating flesh bag",
"Toupeed fucktrumpet",
"Incompressible jizztrumpet",
"Tiny fingered, Cheeto-faced, ferret wearing shitgibbon",
"Cockwomble",
// rick wilson
"President Postliterate Bestwords",
"President Trumphausen",
// other
"Treason Weasel",
"Gropenfuhrer",
// https://www.quora.com/What-derogatory-nicknames-are-people-using-for-President-Trump
// https://www.reddit.com/r/TrumpNicknames/top/?sort=top&t=all
"Tangerine Wankmaggot",
"Just Another Prick With No Wall",
"Frito Bandito",
"The Ku Klux Conman",
"Trumpanzee",
"BLOATUS",
"Agolf Twittler",
"Maga-Lardo",
"Diaper Shitsmear",
"BLOTUS (Big Loud Orangutan of The United States)",
"Cadet Bone Spurs",
"Fucking Moron",
"Super Callous Fragile Racist Sexist NAZI POTUS",
"Cinnamon Hitler",
"Mango Unchained",
"Super Callous Fragile Racist Extra Braggadocious",
"The Cuckwork Orange",
"Mrs. Donald Putin",
// https://pbs.twimg.com/media/EeSV-soXoAEY0p1.jpg
"Klan Chowder",
"Turd Reich",
"Mayonnaise Sculpture",
"Public Access Caligula",
"Hospital Laundry",
"Calamari Lips",
"Pariah Carey",
"Chicken Littlehands",
"Traitor the Hutt",
"Full Diaper",
"Lumbering Garbage Barge",
"Daddy Nobucks",
"Macaulay Sulkin'",
"Illiterate Nero",
"Nazimodo",
"Resting Crime Face",
"Census Whitener",
"Charm Vacuum",
"Grabby Wan Kenobi",
"Kremlin Debt",
"Friendless Urinal Cake",
"Quisling of Queens",
"Crime Champ",
"Narcisyphilis",
"Dumb Sauron",
"Summa Cum Fraude",
"Ass Menagerie",
"Baby Whisper Skin",
"White Pride Piper",
"Flesh Cavern Turkeythroat",
"Nocabulary",
"Community Theater Strongman",
"Fragile Shit Dumpster",
"Idiot Kristallnacht",
"Honey Baked Flim-Flam Man",
"Whopper with Crime",
"Treason Weasel",
"Late Stage Anakin Skywalker",
"Piece of Fucking Shit"
);
function makeHaiku(where) {
	var haiku="";
	var name=Math.floor(Math.random()*names.length);
	where.innerHTML="<p>"+names[name]+"</p>";
}
function go(where) {
	makeHaiku(document.getElementById('h'));
//	Effect.Appear('h', {duration:.3})
}
function all() {
	var s = "";
	for (var name=0; name<names.length; name++) {
		s += "<p>" + names[name] + "</p>";
	}                              
	document.getElementById("all").innerHTML = s;
}
